#lang racket/base
(require "../static/sumtype.rkt")

(define-sumtype TransactionField1
  (Sender)
  (Fee)
  (FirstValid)
  (FirstValidTime)
  (LastValid)
  (Note)
  (Lease)
  (Receiver)
  (Amount)
  (CloseRemainderTo)
  (VotePK)
  (SelectionPK)
  (VoteFirst)
  (VoteLast)
  (VoteKeyDilution)
  (Type)
  (TypeEnum)
  (XferAsset)
  (AssetAmount)
  (AssetSender)
  (AssetReceiver)
  (AssetCloseTo)
  (GroupIndex))

(define-sumtype GlobalField1
  (MinTxnFee)
  (MinBalance)
  (MaxTxnLife)
  (ZeroAddress)
  (GroupSize))

(define-sumtype Instruction1
  (err)
  (sha256)
  (keccak256)
  (sha512_256)
  (ed25519verify)
  (+)
  (-)
  (/)
  (*)
  (<)
  (>)
  (<=)
  (>=)
  (&&)
  (\|\|)
  (==)
  (!=)
  (!)
  (len)
  (itob)
  (btoi)
  (%)
  (\|)
  (&)
  (^)
  (~)
  (mulw)
  (intcblock uints)
  (intc i)
  (intc_0)
  (intc_1)
  (intc_2)
  (intc_3)
  (bytecblock bytess)
  (bytec i)
  (bytec_0)
  (bytec_1)
  (bytec_2)
  (bytec_3)
  (arg n)
  (arg_0)
  (arg_1)
  (arg_2)
  (arg_3)
  (txn field)
  (global field)
  (gtxn group-index field)
  (load i)
  (store i)
  (bnz offset)
  (pop)
  (dup))

(provide (sumtype-out Instruction1)
         (sumtype-out TransactionField1)
         (sumtype-out GlobalField1))

(define-sumtype TransactionField2
  TransactionField1
  (TxID)
  (ApplicationID)
  (OnCompletion)
  (ApplicationArgs)
  (NumAppArgs)
  (Accounts)
  (NumAccounts)
  (ApprovalProgram)
  (ClearStateProgram)
  (RekeyTo)
  (ConfigAsset)
  (ConfigAssetTotal)
  (ConfigAssetDecimals)
  (ConfigAssetDefaultFrozen)
  (ConfigAssetUnitName)
  (ConfigAssetName)
  (ConfigAssetURL)
  (ConfigAssetMetadataHash)
  (ConfigAssetManager)
  (ConfigAssetReserve)
  (ConfigAssetFreeze)
  (ConfigAssetClawback)
  (FreezeAsset)
  (FreezeAssetAccount)
  (FreezeAssetFrozen))

(define-sumtype GlobalField2
  GlobalField1
  (LogicSigVersion)
  (Round)
  (LatestTimestamp)
  (CurrentApplicationID))

(define-sumtype AssetParamsField2
  (AssetTotal)
  (AssetDecimals)
  (AssetDefaultFrozen)
  (AssetUnitName)
  (AssetName)
  (AssetURL)
  (AssetMetadataHash)
  (AssetManager)
  (AssetReserve)
  (AssetFreeze)
  (AssetClawback))

(define-sumtype AssetHoldingField2
  (AssetBalance)
  (AssetFrozen))

(define-sumtype Instruction2
  Instruction1
  (addw)
  (txna field array-index)
  (gtxna group-index field array-index)
  (bz offset)
  (b offset)
  (return)
  (dup2)
  (concat)
  (substring start end)
  (substring3)
  (balance)
  (app_opted_in)
  (app_local_get)
  (app_local_get_ex)
  (app_global_get)
  (app_global_get_ex)
  (app_local_put)
  (app_global_put)
  (app_local_del)
  (app_global_del)
  (asset_holding_get field)
  (asset_params_get field))

(provide (sumtype-out Instruction2)
         (sumtype-out TransactionField2)
         (sumtype-out GlobalField2)
         (sumtype-out AssetParamsField2)
         (sumtype-out AssetHoldingField2))

(define-sumtype TransactionField3
  TransactionField2
  (Assets)
  (NumAssets)
  (Applications)
  (NumApplications)
  (GlobalNumUint)
  (GlobalNumByteSlice)
  (LocalNumUint)
  (LocalNumByteSlice))

(define-sumtype GlobalField3
  GlobalField2
  (CreatorAddress))

(define-sumtype Instruction3
  Instruction2
  (gtxns field)
  (gtxnsa field array-index)
  (assert)
  (dig n)
  (swap)
  (select)
  (getbit)
  (setbit)
  (getbyte)
  (setbyte)
  (min_balance)
  (pushbytes bytes)
  (pushint uint))

(provide (sumtype-out Instruction3)
         (sumtype-out TransactionField3)
         (sumtype-out GlobalField3))

(define-sumtype TransactionField4
  TransactionField3
  (ExtraProgramPages))

(define-sumtype Instruction4
  Instruction3
  (divmodw)
  (gload group-index i)
  (gloads i)
  (gaid group-index)
  (gaids)
  (callsub offset)
  (retsub)
  (shl)
  (shr)
  (sqrt)
  (bitlen)
  (exp)
  (expw)
  (b+)
  (b-)
  (b/)
  (b*)
  (b<)
  (b>)
  (b<=)
  (b>=)
  (b==)
  (b!=)
  (b%)
  (b\|)
  (b&)
  (b^)
  (b~)
  (bzero))

(provide (sumtype-out Instruction4)
         (sumtype-out TransactionField4))

(define-sumtype TransactionField5
  TransactionField4
  (Nonparticipation)
  (Logs)
  (NumLogs)
  (CreatedAssetID)
  (CreatedApplicationID))

(define-sumtype GlobalField5
  GlobalField3
  (CurrentApplicationAddress)
  (GroupID))

(define-sumtype AppParamsField5
  (AppApprovalProgram)
  (AppClearStateProgram)
  (AppGlobalNumUint)
  (AppGlobalNumByteSlice)
  (AppLocalNumUint)
  (AppLocalNumByteSlice)
  (AppExtraProgramPages)
  (AppCreator)
  (AppAddress))

(define-sumtype AssetParamsField5
  AssetParamsField2
  (AssetCreator))

(define-sumtype Instruction5
  Instruction4
  (ecdsa_verify v)
  (ecdsa_pk_decompress v)
  (ecdsa_pk_recover v)
  (loads)
  (stores)
  (cover n)
  (uncover n)
  (extract start length)
  (extract3)
  (extract_uint16)
  (extract_uint32)
  (extract_uint64)
  (app_params_get field)
  (log)
  (itxn_begin)
  (itxn_field field)
  (itxn_submit)
  (itxn field)
  (itxna field array-index)
  (txnas field)
  (gtxnas group-index field)
  (gtxnsas field)
  (args))

(provide (sumtype-out Instruction5)
         (sumtype-out TransactionField5)
         (sumtype-out GlobalField5)
         (sumtype-out AppParamsField5)
         (sumtype-out AssetParamsField5))

(define-sumtype Instruction6
  Instruction5
  (itxn_next))

(provide (sumtype-out Instruction6))

